LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE    := trippingImageMogrifier
LOCAL_SRC_FILES := mogrify_ndk_bridge.c      \
				   filters/analyze.c		 \
				   coders/aai.c              \
				   coders/art.c              \
				   coders/avs.c              \
				   coders/bgr.c              \
				   coders/bmp.c              \
				   coders/braille.c          \
				   coders/cals.c             \
				   coders/caption.c          \
				   coders/cin.c              \
				   coders/cip.c              \
				   coders/clipboard.c        \
				   coders/clip.c             \
				   coders/cmyk.c             \
				   coders/cut.c              \
				   coders/dcm.c              \
				   coders/dds.c              \
				   coders/debug.c            \
				   coders/dib.c              \
				   coders/djvu.c             \
				   coders/dng.c              \
				   coders/dot.c              \
				   coders/dps.c              \
				   coders/dpx.c              \
				   coders/emf.c              \
				   coders/ept.c              \
				   coders/exr.c              \
				   coders/fax.c              \
				   coders/fd.c               \
				   coders/fits.c             \
				   coders/fpx.c              \
				   coders/gif.c              \
				   coders/gradient.c         \
				   coders/gray.c             \
				   coders/hald.c             \
				   coders/hdr.c              \
				   coders/histogram.c        \
				   coders/hrz.c              \
				   coders/html.c             \
				   coders/icon.c             \
				   coders/info.c             \
				   coders/inline.c           \
				   coders/ipl.c              \
				   coders/jbig.c             \
				   coders/jnx.c              \
				   coders/jp2.c              \
				   coders/jpeg.c             \
				   coders/json.c             \
				   coders/label.c            \
				   coders/mac.c              \
				   coders/magick.c           \
				   coders/map.c              \
				   coders/mask.c             \
				   coders/mat.c              \
				   coders/matte.c            \
				   coders/meta.c             \
				   coders/miff.c             \
				   coders/mono.c             \
				   coders/mpc.c              \
				   coders/mpeg.c             \
				   coders/mpr.c              \
				   coders/msl.c              \
				   coders/mtv.c              \
				   coders/mvg.c              \
				   coders/null.c             \
				   coders/otb.c              \
				   coders/palm.c             \
				   coders/pango.c            \
				   coders/pattern.c          \
				   coders/pcd.c              \
				   coders/pcl.c              \
				   coders/pcx.c              \
				   coders/pdb.c              \
				   coders/pdf.c              \
				   coders/pes.c              \
				   coders/pict.c             \
				   coders/pix.c              \
				   coders/plasma.c           \
				   coders/png.c              \
				   coders/pnm.c              \
				   coders/preview.c          \
				   coders/ps2.c              \
				   coders/ps3.c              \
				   coders/ps.c               \
				   coders/psd.c              \
				   coders/pwp.c              \
				   coders/raw.c              \
				   coders/rgb.c              \
				   coders/rgf.c              \
				   coders/rla.c              \
				   coders/rle.c              \
				   coders/scr.c              \
				   coders/screenshot.c       \
				   coders/sct.c              \
				   coders/sfw.c              \
				   coders/sgi.c              \
				   coders/sixel.c            \
				   coders/stegano.c          \
				   coders/sun.c              \
				   coders/svg.c              \
				   coders/tga.c              \
				   coders/thumbnail.c        \
				   coders/tiff.c             \
				   coders/tile.c             \
				   coders/tim.c              \
				   coders/ttf.c              \
				   coders/txt.c              \
				   coders/uil.c              \
				   coders/url.c              \
				   coders/uyvy.c             \
				   coders/vicar.c            \
				   coders/vid.c              \
				   coders/viff.c             \
				   coders/vips.c             \
				   coders/wbmp.c             \
				   coders/webp.c             \
				   coders/wmf.c              \
				   coders/wpg.c              \
				   coders/xbm.c              \
				   coders/x.c                \
				   coders/xc.c               \
				   coders/xcf.c              \
				   coders/xpm.c              \
				   coders/xps.c              \
				   coders/xwd.c              \
				   coders/ycbcr.c            \
				   coders/yuv.c              \
				   wand/pixel-iterator.c	 \
				   wand/conjure.c            \
				   wand/stream.c             \
				   wand/compare.c            \
				   wand/convert.c            \
				   wand/montage.c            \
				   wand/wand-view.c          \
				   wand/display.c            \
				   wand/identify.c           \
				   wand/import.c             \
				   wand/magick-property.c    \
				   wand/pixel-wand.c         \
				   wand/animate.c            \
				   wand/drawing-wand.c       \
				   wand/composite.c          \
				   wand/deprecate.c          \
				   wand/wand.c               \
				   wand/mogrify.c            \
				   wand/magick-image.c       \
				   wand/magick-wand.c        \
				   magick/client.c           \
				   magick/xwindow.c          \
				   magick/exception.c        \
				   magick/profile.c          \
				   magick/log.c              \
				   magick/feature.c          \
				   magick/widget.c           \
				   magick/signature.c        \
				   magick/nt-base.c          \
				   magick/monitor.c          \
				   magick/statistic.c        \
				   magick/resample.c         \
				   magick/xml-tree.c         \
				   magick/quantize.c         \
				   magick/quantum-export.c   \
				   magick/vms.c              \
				   magick/histogram.c        \
				   magick/stream.c           \
				   magick/artifact.c         \
				   magick/compare.c          \
				   magick/cache-view.c       \
				   magick/static.c           \
				   magick/montage.c          \
				   magick/cache.c            \
				   magick/version.c          \
				   magick/geometry.c         \
				   magick/effect.c           \
				   magick/display.c          \
				   magick/locale.c           \
				   magick/accelerate.c       \
				   magick/channel.c          \
				   magick/segment.c          \
				   magick/vision.c           \
				   magick/distort.c          \
				   magick/identify.c         \
				   magick/blob.c             \
				   magick/quantum.c          \
				   magick/splay-tree.c       \
				   magick/quantum-import.c   \
				   magick/draw.c             \
				   magick/thread.c           \
				   magick/magick.c           \
				   magick/utility.c          \
				   magick/magic.c            \
				   magick/image-view.c       \
				   magick/layer.c            \
				   magick/compress.c         \
				   magick/cipher.c           \
				   magick/enhance.c          \
				   magick/PreRvIcccm.c       \
				   magick/fx.c               \
				   magick/coder.c            \
				   magick/hashmap.c          \
				   magick/module.c           \
				   magick/animate.c          \
				   magick/attribute.c        \
				   magick/distribute-cache.c \
				   magick/list.c             \
				   magick/paint.c            \
				   magick/memory.c           \
				   magick/color.c            \
				   magick/option.c           \
				   magick/configure.c        \
				   magick/colormap.c         \
				   magick/pixel.c            \
				   magick/annotate.c         \
				   magick/image.c            \
				   magick/policy.c           \
				   magick/transform.c        \
				   magick/fourier.c          \
				   magick/gem.c              \
				   magick/matrix.c           \
				   magick/mac.c              \
				   magick/prepress.c         \
				   magick/random.c           \
				   magick/composite.c        \
				   magick/timer.c            \
				   magick/resize.c           \
				   magick/type.c             \
				   magick/constitute.c       \
				   magick/threshold.c        \
				   magick/mime.c             \
				   magick/resource.c         \
				   magick/opencl.c           \
				   magick/colorspace.c       \
				   magick/morphology.c       \
				   magick/string.c           \
				   magick/deprecate.c        \
				   magick/registry.c         \
				   magick/nt-feature.c       \
				   magick/shear.c            \
				   magick/decorate.c         \
				   magick/property.c         \
				   magick/token.c            \
				   magick/semaphore.c        \
				   magick/delegate.c         \

LOCAL_LDLIBS += -lm -lz -llog

include $(BUILD_SHARED_LIBRARY)
